require:
  - rubocop-rspec
  - rubocop-rails

AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Metrics/AbcSize:
  Exclude:
    - 'db/migrate/*'

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*'

RSpec/EmptyExampleGroup:
  Exclude:
    - 'spec/requests/api/**/*'

RSpec/MultipleMemoizedHelpers:
  Max: 8

RSpec/MultipleExpectations:
  Exclude:
    - 'spec/features/**/*'

RSpec/NestedGroups:
  Max: 5