version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.development
    ports:
      - 3000:3000
    volumes:
      - .:/home/data-catalogue
      - gem_cache:/usr/local/bundle
    depends_on:
      - db
    environment:
      - HTTP_PASSWORD=cddo-pwd
      - HTTP_USERNAME=cddo-team
      - RAILS_ENV=development
    
  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - db_data:/home/data-catalogue/tmp/data:/var/lib/postgresql/data

  redis:
    image: redis:6.2-alpine
    ports:
      - 6379:6379
  
  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile.development
    depends_on:
      - db
      - redis
      - web
    volumes:
      - .:/home/data-catalogue
      - gem_cache:/usr/local/bundle
    entrypoint: ./bin/start_sidekiq.sh
    environment:
      RAILS_ENV: development
  
volumes:
  db_data:
  gem_cache:
