
version: '3.7'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.development
    ports:
      - "3000:3000"
    volumes:
      - .:/home/data-catalogue
    depends_on:
      - db
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=postgres://postgres:postgres@db/data_catalogue_development
    
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./tmp/data:/var/lib/postgresql/data
