version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.development
    ports:
      - 3000:3000
    volumes:
      - .:/home/data-catalogue
      - bundle_path:/bundle 
    depends_on:
      - db
    environment:
      - BUNDLE_PATH=/bundle/vendor
      - HTTP_PASSWORD=cddo-pwd
      - HTTP_USERNAME=cddo-team
      - RAILS_ENV=development
    
  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - ./tmp/data:/var/lib/postgresql/data

  redis:
    image: redis:6.2-alpine
    ports:
      - 6379:6379
  
  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile.development
    depends_on:
      - db
      - redis
      - web
    volumes:
      - .:/home/data-catalogue
    entrypoint: ./bin/start_sidekiq.sh
    environment:
      RAILS_ENV: development
  
volumes:
  bundle_path:
