version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.development
    ports:
      - "3000:3000"
    volumes:
      - .:/home/data-catalogue
    depends_on:
      - db
    environment:
      - HTTP_PASSWORD=cddo-pwd
      - HTTP_USERNAME=cddo-team
      - RAILS_ENV=development
    
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./tmp/data:/var/lib/postgresql/data
