---
openapi: 3.0.1
info:
  title: DataCatalogue API V1
  version: v1
components:
  securitySchemes:
    basic_auth:
      type: http
      scheme: basic
paths:
  "/api/v1/data_services":
    post:
      summary: create data service
      operationId: post_data_service
      description: Creates a new data service
      security:
      - basic_auth: []
      parameters: []
      responses:
        '201':
          description: created
        '422':
          description: unprocessable_entity
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                data_service:
                  type: object
                  properties:
                    enpoint_url:
                      type: string
                      format: url
                    endpoint_description:
                      type: string
                    serves_data:
                      type: array
                      items:
                        type: string
                        format: url
                    service_type:
                      type: string
                      enum:
                      - EVENT
                      - REST
                      - SOAP
                    service_status:
                      type: string
                      enum:
                      - ALPHA
                      - BETA
                      - PRIVATE_BETA
                      - PUBLIC_BETA
                      - PRODUCTION
                      - DEPRECATED
                      - WITHDRAWN
                    identifier:
                      type: string
                    title:
                      type: string
                    description:
                      type: string
                    keywords:
                      type: array
                      items:
                        type: string
                    themes:
                      type: array
                      items:
                        type: string
                    licence:
                      type: string
                      format: url
                    version:
                      type: string
                    contact_name:
                      type: string
                    contact_email:
                      type: string
                      format: email
                    alternative_titles:
                      type: array
                      items:
                        type: string
                    access_rights:
                      type: string
                      enum:
                      - INTERNAL
                      - OPEN
                      - COMMERCIAL
                    security_classification:
                      type: string
                      enum:
                      - OFFICIAL
                      - OFFICIAL_SENSITIVE
                      - SECRET
                      - TOP_SECRET
                    issued:
                      type: string
                      format: date
                    modified:
                      type: string
                      format: datetime
                    creators:
                      type: array
                      items:
                        type: string
                    publisher:
                      type: string
                    related_data_resources:
                      type: array
                      items:
                        type: string
                        format: uuid
                    summary:
                      type: string
                    created:
                      type: string
                      format: date
                  required:
                  - endpoint_description
                  - service_status
                  - contact_name
                  - contact_email
                  - version
                  - access_rights
                  - security_classification
                  - creator
                  - publisher
                  - description
                  - identifier
                  - licence
                  - modified
                  - title
              required:
              - data_service
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: data-catalogue-staging.herokuapp.com/
