default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  port: 5432
  encoding: unicode
  host: <%= ENV.fetch('DATABASE_HOSTtemp', 'db') %>
  username: <%= ENV.fetch('DATABASE_USERNAME', 'postgres') %>
  password: <%= ENV.fetch('DATABASE_PASSWORD', 'postgres') %>

development:
  <<: *default
  database: <%= ENV.fetch('DATABASE_NAME') %>

test:
  <<: *default
  database: <%= ENV.fetch('DATABASE_NAME') %>

production:
  <<: *default
  database: <%= ENV.fetch('DATABASE_NAME') %>
