default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  port: 5432
  encoding: unicode
  
development:
  <<: *default
  database: <%= ENV.fetch('DATABASE_URL') %>

test:
  <<: *default
  database: <%= ENV.fetch('DATABASE_URL') %>

production:
  <<: *default
  database: <%= ENV.fetch('DATABASE_URL') %>
